#!/usr/bin/env bash

set -euo pipefail  # exit on errors and unset vars, and stop on the first error in a "pipeline"

input=${1:-$(iso8601 date)}

case "${input}" in
    "help" | "--help")
    echo "Moves the current contents of ~/Notes/scratch to a backup under ~/Old-Notes"
    exit 0
    ;;

esac

mv ~/Notes/scratch ~/Old-Notes/old-scratch/save-${input}
mkdir ~/Notes/scratch
